language: ruby
node_js:
  - '5.3.0'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
sudo: false
cache:
  bundler: true
  directories:
    - node_modules
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: g9QLZyMW8898EIjme/2YgQW78iH48n3DHZWJv7V8RCjOdA0p9VePMYGitO31PWpiASO3tYGD26EB5PpnG7eRKcP771Ae4gX7MrrefQEDtecryY9YVsMn/uhDQ+29so4F50LQ+7ffUgJbkHCJdh/Pqwhz6plK9hzqq4AAHnBsPa56urnu8Wa7T2lAJNdErHn20ySaX5NT/CZvWN7c+SfJT0h/EVk1lzeNIinyS+3K52sIc1k2t5iLVlq3X2qOjuXQKOYDedd9g9CSGPJ2dAzk2W7msfb3QCM6Ms9QznqbNYxbvZtwLD24yhydrBR93BAkpV3oypeQkhJy3qH/RLV0A6xTsIbtS492gP6P9WDWuqiIN5LFYdKyrnRz2Np3qjHKiX6nejxJ5nUOrEFD1Mxrkp3KWF0IOtR+s7J8qLdJTPDRm0eL73Bzowhfh3dZfu3gVVu6Ul+kf2VWDCYlquCdnnojfRwWwAoNhTNugk8iJ25oxRuiOQfvI9uxv+ms267uVICB8hrYiJvMgy+x7o79z4o7PsNO6NIHcrzubdNoNCH5IWfog/pcxkwiL4rH0J4M1c2s2kdev0sEJmwYQS/9LpWdGyAhG3N3zAPkQ5rnX9bHLFHmWMsW/np39CN5FoYbknQCbTxlWqY3mK+zMNOq5SCfZ+C7BR9h5IeRudgBidY=
  - secure: QIOU8S8s7jrUWrcElECC1et6qLUS+DxCkDdTBeX+EcHJbEZULu0GFrDEF7sLGXkl1pDiNQMHTIAYhYONFythKv46kKgNirT8PU6ElTecWCYTKrq7T/hS0+kzSW/WzffY+M/C8Fbu3e0IaJs6dBT4U8h97UiCVrPZ0aaTM0ObgxoSBTAz035J+SHYwbcaCZ2+m8jIPoFNl4JJx0Tr7cdKwrUaBg0+vtGgvRhPNPY/k0Cf1WlYGSrsXAEhK7h68rCx3QN8rRRuk4ADlLq8AMPaOZzV2SOc3+LGgWWPCWJnLcA96aFGBrlbrQsw/bnnaLGhJSgyVyheDyq8w/Jkp+MvGVNMO1tr2arRqPoOD9Uwv+Aa5fKH9Ndmv9ANvVz42ibMo8KPTq2IckIgZPovz1tNbfBRzgh0ls29qfVoNaaK82rJfcc151TA01rMUDwhH4R/K/z1xDBJ8nknuSsTF5MuuYVyMRDqvOsRoY8DTUY3KPVYht67kyhQLQlBV/Ra/0CGxpoGtWw/RUiipD35Vbbq+2KVjazKI/CNtV8nFWyFdLVW1GL0/mgwTxsw3jP1GZ+PcpA8vVLnKcHfEM7nuKZjVg1CsCYi34yNVpuYx5xdOf9Wijrv2IM8qHVS4NtZJU8Lagp7buKqn3VIni1jwG33yddt9CIMWxcCchMR3sEFP8g=
  - secure: g6E1FFjc6qEe61imAoULC7UItBaTQzHrFn+3FiYTcLHJTKGGsf1fQ6aWWL2tDaxFYZRBgVXfpqQXXgt4PWL7lfTeLpwi40rnv+6HBuvjr0hdTISU6PmNZG7PUZ8BPuN5sC7xq9RQZIsJxbroeL/g4vLtguEVJ4MP9Gq0aOedvNmx2cx/jwROt8RFV0gqT5VJE66vfCcacoIVZo2K6CK3yZJeJW01Cpq7w/lio3jOv8IuJK0V298VVTK5QsqyHH0o0ZfFIPe3caL8i5R7JHxEKKnGAYVtyfM+JE6bds2AFXIP2POu0CerCBWepMgpi/9OgJm2Jw3RjxRy0ADkD8/vzs/hwbTqaC6MhNAnk+RUvaGuSfLRjmyXX8USzlQhabYNzaR2l9/F3jJDCtJiClGzoY8aeV3uPdLrYQf7/5nbcetg+frHlv0LCVnevEVW+QNSUlH3qxLN3h4OrR3TePVOuiyscd4YKgGiwUtT2RdwURokTiY4jI9fjIN3xOLM/aQzHC+EnfAiur4e7jXO7n4wnsWZ1Mm4AqyStSrftxafFV7xnxLbqC0o6O/f7rgZDmjsDFMrfq3zm6JnzaiMQRU0xJGvFHV+JFhds0bCT7BNvsSvIsAlFm3YSgGpMVbFPLGvomJLpxR8S4j3kDyKNfd43aCYzFYM6/JLP0SjZtO2/gg=
before_install:
- openssl aes-256-cbc -K $encrypted_00d3eca46daa_key -iv $encrypted_00d3eca46daa_iv
  -in config/travis/travis_rsa.enc -out ~/.ssh/id_rsa -d
- git config --global user.name "${GIT_NAME}"
- git config --global user.email "${GIT_EMAIL}"
- npm install -g npm@'>=3.3.6'
install:
- bundle install
- npm install
before_script:
  - git clone https://${GH_TOKEN}@github.com/benkutil/benkutil.github.io.git --branch master --single-branch dist/
  - gulp build
  - eval "$(ssh-agent)"
  - chmod 600 ~/.ssh/id_rsa
  - ssh-add
script:
  - npm test
  - htmlproof ./dist
after_success:
  - cd dist
  - git add -A
  - git commit -m ':shipit:'" Production Build from ${TRAVIS_COMMIT}"
  - git push origin HEAD:master
  - cd ../
  - bundle exec cap production deploy
