# Source Settings
source: source/
destination: tmp/
exclude: [
    'styles',
    'media/source',
    'media/favicons'
]

# Site Settings
title: Ben Kutil<span class="hide"> - Product Manager, Designer, Educator, Baker</span>
description: >
    A systems-focused product manager who designs, codes, teaches, and bakes.
email: thisis@benkutil.com
github_username: benkutil
twitter_username: benkutil

# Jekyll Configuration
baseurl: ""
excerpt_separator: ""
markdown: redcarpet
plugins:
    - jekyll-picture-tag

# Defaults
defaults:
    -
        scope:
            path: "" # an empty string here means all files in the project
            type: "posts"
        values:
            layout: "post"
            tagline: ""
            published: false
            meta: false
    -
        scope:
            path: "" # an empty string here means all files in the project
            type: "recipes"
        values:
            layout: "page"
            tagline: ""
            published: false
            meta: false
    -
        scope:
            path: "" # an empty string here means all files in the project
            type: "consumables"
        values:
            layout: "page"
            tagline: ""
            published: false
            meta: false
    -
        scope:
            path: "" # an empty string here means all files in the project
            type: "portfolio"
        values:
            layout: "project"
            tagline: ""
            published: false
            meta: false
    -
        scope:
            path: "" # an empty string here means all files in the project
            type: "applications"
        values:
            layout: "project"
            tagline: ""
            published: false
            meta: false

# Collections
collections:
    recipes:
        output: true
        permalink: /cooks/:path/
    consumables:
        output: true
        permalink: /consumes/:path/
    portfolio:
        output: true
        permalink: /designs/:slug/
    applications:
        output: true
        permalink: /applies/to/:path/

# Plugin Details

# Redcarpet
redcarpet:
    extensions: ["with_toc_data"]
#
# Picture
picture:
    source: "source/media/source"
    output: "media/generated"
    markup: picture
    suppress_warnings: false
    presets:
        default:
            ppi: [1, 2]
            attr:
                class: block
                itemprop: image
            source_large:
                media: "(min-width: 52em)"
                width: 1312
            source_medium:
                media: "(min-width: 52em)"
                width: 1024
            source_small:
                media: "(min-width: 25em)"
                width: 640
            source_default:
                width: 375
        work-thumb:
            ppi: [1, 2]
            attr:
                itemprop: image
            source_small:
                media: "(min-width: 40em)"
                width: 576
            source_default:
                width: 375
