# Source Settings
source: source/
destination: tmp/
exclude: [
    'source/styles'
]

# Site Settings
title: Ben Kutil
description: >
    A systems-obsessed product designer who codes, teaches, and bakes.
email: thisis@benkutil.com
github_username: benkutil
twitter_username: benkutil

# Jekyll Configuration
baseurl: ""
excerpt_separator: ""
markdown: redcarpet
gems: [jekyll-picture-tag]

# Defaults
defaults:
    -
        scope:
            path: "" # an empty string here means all files in the project
            type: "posts"
        values:
            layout: "posts"
            tagline: ""
    -
        scope:
            path: "" # an empty string here means all files in the project
            type: "recipes"
        values:
            layout: "page"
            tagline: ""
    -
        scope:
            path: "" # an empty string here means all files in the project
            type: "consumables"
        values:
            layout: "page"
            tagline: ""
    -
        scope:
            path: "" # an empty string here means all files in the project
            type: "portfolio"
        values:
            layout: "page"
            tagline: ""

# Collections
collections:
    recipes:
        output: true
        permalink: /cooks/:path/
    consumables:
        output: true
        permalink: /consumes/:path/
    portfolio:
        output: true
        permalink: /designs/:path/

# Plugin Details
#
# Picture
picture:
    source: media
    output: media/generated
    markup: picture
    presets:
        default:
            ppi: [1, 2]
            attr:
                class: block
                itemprop: image
            source_lrg:
                media: "(min-width: 40em)"
                width: 768
            source_med:
                media: "(min-width: 30em)"
                width: 550
            source_default:
                width: 375
                height: 375
        half:
            ppi: [1, 2]
            attr:
                data-location: "{{location}}"
                data-active: nil
            source_lrg:
                media: "(min-width: 40em)"
                width: 350
            source_med:
                media: "(min-width: 30em)"
                width: 275
            source_default:
                width: 188
        gallery:
            source_wide_hi:
                media: "(min-width: 40em) and (min-resolution: 1.5dppx)"
                width: 900
                height: 600
            source_wide:
                media: "(min-width: 40em)"
                width: 600
                height: 400
            source_default:
                width: 250
                height: 250
