# App Settings
source: source/
destination: tmp/
exclude: [
  'source/styles'
]

title: > #
  Ben Kutil, Product Designer, Teacher, Baker
description: > #
  A goal for 2016, keeping a consistent website.
email: thisis@benkutil.com
github_username: benkutil
twitter_username: benkutil

baseurl: "" # the subpath of your site, e.g. /blog/

# Editing settings
markdown: redcarpet

collections:
  recipes:
    output: true
    permalink: /cooks/:path/
  consumables:
    output: true
    permalink: /consumes/:path/
  portfolio:
    output: true
    permalink: /makes/:path/

gems: [jekyll-picture-tag]

picture:
  source: media
  output: media/generated
  markup: picture
  presets:
    # Full width pictures
    default:
      ppi: [1, 2]
      attr:
        class: blog-full
        itemprop: image
      source_lrg:
        media: "(min-width: 40em)"
        width: 700
      source_med:
        media: "(min-width: 30em)"
        width: 550
      source_default:
        width: 375
        height: 375
    # Half width pictures
    half:
      ppi: [1, 2]
      attr:
        data-location: "{{location}}"
        data-active: nil
      source_lrg:
        media: "(min-width: 40em)"
        width: 350
      source_med:
        media: "(min-width: 30em)"
        width: 275
      source_default:
        width: 188
    # Self-set resolution sources. Useful if you don't want a 1:1 image size to dppx ratio.
    gallery:
      source_wide_hi:
        media: "(min-width: 40em) and (min-resolution: 1.5dppx)"
        width: 900
        height: 600
      source_wide:
        media: "(min-width: 40em)"
        width: 600
        height: 400
      source_default:
        width: 250
        height: 250
