name: Build Jekyll Site

on:
  push:
    branches:
      - develop
            

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        # Checks out code
        - name: checkout
          uses: actions/checkout@v2
    
        # Cached/ Pre-built ruby for faster build times
        # [ruby/setup-ruby](https://github.com/ruby/setup-ruby)
        - name: setup
          uses: ruby/setup-ruby@v1
          with:
            bundler-cache: true
                
        # jekyll-action-ts to build jekyll
        # https://github.com/limjh16/jekyll-action-ts
        - name: build
          uses: limjh16/jekyll-action-ts@v2
          with:
            enable_cache: true

        # deploy to server using SCP
        - name: scp
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.REMOTE_HOST }}
            username: ${{ secrets.REMOTE_USER }}
            password: ${{ secrets.REMOTE_PASSWORD }}
            rm: false
            source: ./_site
            target: ${{ secrets.REMOTE_PATH }}/test